# core/brain_router.py

from core.sifra_core import SifraCore


class SifraBrain:
    """
    Unified Router:
    - Accepts any data + goal
    - Runs through SIFRA Core
    - Returns structured + natural language insight
    """

    def __init__(self):
        self.brain = SifraCore()

    def run(self, goal, dataset):
        """
        Entry point for:
            - Website
            - API
            - Dashboard
            - Mobile app
        """

        output = self.brain.run(goal, dataset)

        # Attach human-style response (generated by NARE-X NLG)
        natural = output["NAREX"].get("natural_language_response", "")

        return {
            "status": "success",
            "goal": goal,
            "raw_output": output,
            "natural_language_response": natural
        }
