import random

# engine/nlg/auto_template_synthesizer.py

import random

class AutoTemplateSynthesizer:
    """
    Auto-generates human-style text without LLM.
    """

    def __init__(self):
        print("[NLG] Auto Template Synthesizer Ready")

        self.intros = [
            "Here’s what the system discovered:",
            "After analyzing the data, the engine concludes:",
            "Based on the detected patterns, the intelligence engine reports:",
            "Here is the summary generated by NARE-X:"
        ]

        self.volatility_desc = [
            "stable behavior",
            "moderate fluctuations",
            "noticeable variations",
            "increasing pattern movement"
        ]

        self.closings = [
            "This summary reflects the core behavior of your dataset.",
            "These insights offer a clear overview of the detected pattern.",
            "This outlines how the signal is expected to evolve."
        ]

    def generate(self, core, agents, memory):
        mean = core.get("intent_signal", 0)
        vol = core.get("volatility_index", 0)
        trend = agents.get("analysis", {}).get("trend", 0)
        forecast = agents.get("forecast", {}).get("forecast_values", [])
        sim = memory.get("similarity_to_previous", 0)

        intro = random.choice(self.intros)
        vdesc = random.choice(self.volatility_desc)
        closing = random.choice(self.closings)

        text = f"""
{intro}

• Average signal level: **{mean:.2f}**
• Volatility index: **{vol:.2f}** → showing {vdesc}
• Trend momentum: **{trend:.2f}**
• Pattern stability: **{sim:.2f}**

**Forecast Projection**
Next expected values:
{forecast}

{closing}
        """
        return text.strip()

